%%
filter_type                 = 'bandPass'; %      'lowPass' for resp. binning 
                                          % or   'bandPass' for card. binning
nMask                       = 20; % Should be adapted to heart_rate.  
maskWidth                   = 1; 
nSignal_to_select           = 20; % 1 manually, untrended, selected signal for resp. binning
                                  % 15 to 25 for card. binning. 

signal_exploration_level    = 'medium'; % 'leight' or 'medium' or 'heavy'

p = bmMriAcquisitionParam([]);
p.nCh                         = 42; 
p.N                           = 480; 
p.nSeg                        = 22; 
p.nShot                       = 652;

p.nLine                       = p.nSeg*p.nShot; 
p.nPt                         = p.N*p.nLine; 


%%

reconDir = '/Users/cag/Documents/Dataset/datasets/251114/exploreGradSp/'; 
f = [reconDir, 'meas_MID00367_FID11419_yiwei_grad0.dat']; 

SI = bmTwix_getFirstProjOfShot(f, p); 
% extract the SI projection from the raw data in Twix
% bmIDF: from k-space to image space --> SI
%% getting rmsSI from SI
rmsSI = bmMriPhi_fromSI_rmsSI(SI, p.nCh, p.N, p.nShot); 
% normalized RMS of SI across nCh

%% getting standart_reference_signal from SI

[s_ref, ...
 t_ref, ...
 Fs_ref, ...
 nu_ref, ...
 imNav, ...
 ind_shot_min, ...
 ind_shot_max, ...
 ind_SI_min, ...
 ind_SI_max, ... 
 s_reverse_flag   ] = bmMriPhi_fromSI_get_standart_reference_signal(   rmsSI, ...
                                                                       p.nCh, ...
                                                                       p.N, ...
                                                                       p.nSeg, ...
                                                                       p.nShot ); 
% press s + click min: left click, max: right click: ind_shot 
% press n + click min: left click, max: right click: ind_imNav
% press x + click min: left click, max: right click: ind_N


%% graphical frequency selector
[ s_ref_lowPass, ...
  s_ref_bandPass, ...
  lowPass_filter, ...
  bandPass_filter ] = bmMriPhi_graphical_frequency_selector(  s_ref, ...
                                                              t_ref, ...
                                                              Fs_ref, ...
                                                              nu_ref, ...
                                                              imNav     ); 

                                                          

%% reformated_signal_ref
check_image = rmsSI(ind_SI_min:ind_SI_max, :); 
reformated_signal_ref = bmMriPhi_fromSI_standartSignal_to_reformatedSignal( s_ref_bandPass, ...
                                                                            nSeg, ...
                                                                            nShot, ...
                                                                            ind_shot_min, ...
                                                                            ind_shot_max, ...
                                                                            check_image   ); 

                                                                        
%% extracting reformated_signal_list from SI 
if nSignal_to_select > 1 
    nSignal_to_select_minus_1 = nSignal_to_select - 1; 
    reformated_signal_list = bmMriPhi_fromSI_collect_signal_list(   filter_type, ...
                                                                    t_ref, ...
                                                                    nu_ref, ...
                                                                    SI, ...
                                                                    lowPass_filter, ...
                                                                    bandPass_filter, ...
                                                                    nCh, ...
                                                                    N, ...
                                                                    nSeg, ...
                                                                    nShot, ...
                                                                    nSignal_to_select_minus_1, ...
                                                                    signal_exploration_level, ...
                                                                    ind_shot_min, ...
                                                                    ind_shot_max, ...
                                                                    ind_SI_min, ...
                                                                    ind_SI_max,...
                                                                    s_reverse_flag   );
else
    reformated_signal_list = []; 
end

reformated_signal_list = cat(1, reformated_signal_ref, reformated_signal_list); 


%% computing card phase
[cardPhase, cardPhase_list] = bmMriPhi_signalList_to_phase(  reformated_signal_list  ); 

%% mask_construction
cMask = bmMriPhi_phase_to_mask(cardPhase, nMask, maskWidth); 


















